/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import connection.ConnectionFactory;
import java.awt.FlowLayout;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author emanu
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    public MainFrame() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        menuCadastrarJogador = new javax.swing.JMenuItem();
        menuCadastrarEquipe = new javax.swing.JMenuItem();
        menuCadastrarPartida = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        btnEstatisticaJogador = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        btnBuscarJogador = new javax.swing.JMenuItem();
        menuBuscarEquipe = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("jMenu6");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NBA Statistics");

        jMenu7.setText("Cadastrar");

        menuCadastrarJogador.setText("Cadastrar Jogador");
        menuCadastrarJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarJogadorActionPerformed(evt);
            }
        });
        jMenu7.add(menuCadastrarJogador);

        menuCadastrarEquipe.setText("Cadastrar Equipe");
        menuCadastrarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarEquipeActionPerformed(evt);
            }
        });
        jMenu7.add(menuCadastrarEquipe);

        menuCadastrarPartida.setText("Cadastrar Partida");
        menuCadastrarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarPartidaActionPerformed(evt);
            }
        });
        jMenu7.add(menuCadastrarPartida);

        jMenuBar1.add(jMenu7);

        jMenu2.setText("Estatística");

        jMenu3.setText("Cadastrar");

        btnEstatisticaJogador.setText("Jogador");
        btnEstatisticaJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticaJogadorActionPerformed(evt);
            }
        });
        jMenu3.add(btnEstatisticaJogador);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("Buscar");

        btnBuscarJogador.setText("Jogador");
        btnBuscarJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarJogadorActionPerformed(evt);
            }
        });
        jMenu8.add(btnBuscarJogador);

        menuBuscarEquipe.setText("Equipe");
        menuBuscarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarEquipeActionPerformed(evt);
            }
        });
        jMenu8.add(menuBuscarEquipe);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarJogadorActionPerformed
        // TODO add your handling code here:
        TelaCadastrarJogador cadastrarJogador = new TelaCadastrarJogador(this);
        cadastrarJogador.setVisible(true);
        this.add(cadastrarJogador);
        
    }//GEN-LAST:event_menuCadastrarJogadorActionPerformed

    private void menuCadastrarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarEquipeActionPerformed
        // TODO add your handling code here:
        TelaCadastrarEquipe cadastrarEquipe = new TelaCadastrarEquipe(this);
        cadastrarEquipe.setVisible(true);
        this.add(cadastrarEquipe);
    }//GEN-LAST:event_menuCadastrarEquipeActionPerformed

    private void menuCadastrarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarPartidaActionPerformed
        TelaCadastrarPartida telaPartida = new TelaCadastrarPartida(this);
        telaPartida.setVisible(true);
        this.add(telaPartida);
    }//GEN-LAST:event_menuCadastrarPartidaActionPerformed

    private void btnEstatisticaJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticaJogadorActionPerformed
        // TODO add your handling code here:
        TelaCadastrarEstatisticaJogador t = new TelaCadastrarEstatisticaJogador(this);
        t.setVisible(true);
        this.add(t);
    }//GEN-LAST:event_btnEstatisticaJogadorActionPerformed

    private void btnBuscarJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarJogadorActionPerformed
        // TODO add your handling code here:
        TelaBuscarJogador buscarJogador = new TelaBuscarJogador(this);
        buscarJogador.setVisible(true);
        this.add(buscarJogador);
    }//GEN-LAST:event_btnBuscarJogadorActionPerformed

    private void menuBuscarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarEquipeActionPerformed
        // TODO add your handling code here:
        TelaBuscarEquipe buscarEquipe = new TelaBuscarEquipe(this);
        buscarEquipe.setVisible(true);
        this.add(buscarEquipe);
    }//GEN-LAST:event_menuBuscarEquipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public void popUP(String mensagem){
        JDialog jdialog = new JDialog(this, true);
        jdialog.setSize(200, 200);
        jdialog.setLayout(new FlowLayout());
        jdialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        JLabel label = new JLabel(mensagem);
        jdialog.add(label);
        jdialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnBuscarJogador;
    private javax.swing.JMenuItem btnEstatisticaJogador;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuBuscarEquipe;
    private javax.swing.JMenuItem menuCadastrarEquipe;
    private javax.swing.JMenuItem menuCadastrarJogador;
    private javax.swing.JMenuItem menuCadastrarPartida;
    // End of variables declaration//GEN-END:variables
}
