/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ControllerEquipe;
import controllers.ControllerEstatistica;
import controllers.ControllerJogador;
import controllers.ControllerPartida;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.text.MaskFormatter;
import models.Equipe;
import models.EstatisticaJogador;
import models.Jogador;
import models.Partida;

/**
 *
 * @author emanu
 */
public class TelaCadastrarEstatisticaJogador extends javax.swing.JInternalFrame {
    private MainFrame desktop;
    private ArrayList<Partida> partidas;
    private ArrayList<Jogador> jogadores;
    /**
     * Creates new form TelaCadastrarParida
     */
    public TelaCadastrarEstatisticaJogador(MainFrame desktop){
        initComponents();
        this.desktop = desktop;
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrarEstatisticaJogador = new javax.swing.JButton();
        cmbPartida = new javax.swing.JComboBox<>();
        btnBuscarPartida = new javax.swing.JButton();
        cmbJogador = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spnPontos = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spnRebotes = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        spnAssistencias = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        spnRoubadas = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spnTocos = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        spnTurnovers = new javax.swing.JSpinner();
        txtDataPartida = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Estatística do Jogador");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Patida");
        jLabel1.setAlignmentX(0.5F);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Data da Partida");
        jLabel3.setAlignmentX(0.5F);

        btnCadastrarEstatisticaJogador.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadastrarEstatisticaJogador.setText("Cadastrar");
        btnCadastrarEstatisticaJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEstatisticaJogadorActionPerformed(evt);
            }
        });

        cmbPartida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPartidaItemStateChanged(evt);
            }
        });

        btnBuscarPartida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscarPartida.setText("Buscar");
        btnBuscarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPartidaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Jogador");
        jLabel6.setAlignmentX(0.5F);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Pontos");
        jLabel7.setAlignmentX(0.5F);

        spnPontos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Rebotes");
        jLabel8.setAlignmentX(0.5F);

        spnRebotes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Assistencias");
        jLabel9.setAlignmentX(0.5F);

        spnAssistencias.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Roubadas");
        jLabel10.setAlignmentX(0.5F);

        spnRoubadas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Tocos");
        jLabel11.setAlignmentX(0.5F);

        spnTocos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Turnovers");
        jLabel12.setAlignmentX(0.5F);

        spnTurnovers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtDataPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(44, 44, 44)
                                .addComponent(cmbJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(110, 110, 110)
                                .addComponent(spnPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(98, 98, 98)
                                .addComponent(spnRebotes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(60, 60, 60)
                                .addComponent(spnAssistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(84, 84, 84)
                                .addComponent(spnRoubadas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(118, 118, 118)
                                .addComponent(spnTocos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(81, 81, 81)
                                .addComponent(spnTurnovers, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDataPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnCadastrarEstatisticaJogador)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPartida))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cmbPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cmbJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spnPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spnRebotes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spnAssistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spnRoubadas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spnTocos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spnTurnovers, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarEstatisticaJogador)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarEstatisticaJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEstatisticaJogadorActionPerformed
        int indexJogador = cmbJogador.getSelectedIndex();
        int indexPartida = cmbPartida.getSelectedIndex();
        if(indexJogador >= 0 && indexPartida >= 0){
            ControllerEstatistica controllerEstatistica = new ControllerEstatistica();
            Jogador jogador = this.jogadores.get(indexJogador);
            Partida partida = this.partidas.get(indexPartida);
            Integer pontos = Integer.parseInt(spnPontos.getValue().toString());
            Integer rebotes = Integer.parseInt(spnRebotes.getValue().toString());
            Integer assistencias = Integer.parseInt(spnAssistencias.getValue().toString());
            Integer roubadas = Integer.parseInt(spnRoubadas.getValue().toString());
            Integer tocos = Integer.parseInt(spnTocos.getValue().toString());
            Integer turnovers = Integer.parseInt(spnTurnovers.getValue().toString());

            EstatisticaJogador estatisticaJogador = new EstatisticaJogador(partida, jogador, pontos, rebotes, assistencias, roubadas, tocos, turnovers);

            boolean cadastro = controllerEstatistica.createEstatisticaJogador(estatisticaJogador);
            if(cadastro){
                this.desktop.popUP("Cadastrado com sucesso!");
                this.dispose();
            }else{
                this.desktop.popUP("Erro ao cadastrar estatística! Por favor verifique os dados inseridos.");
            }
        }else{
            System.out.println(indexJogador);
            System.out.println(indexPartida);
        }
    }//GEN-LAST:event_btnCadastrarEstatisticaJogadorActionPerformed

    private void btnBuscarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPartidaActionPerformed
        // TODO add your handling code here:
        ControllerPartida cp = new ControllerPartida();
        String data = txtDataPartida.getText();
        this.partidas = new ArrayList();
        this.partidas = cp.getByData(data);
        cmbPartida.removeAllItems();
        for(Partida p : partidas){
            cmbPartida.addItem(p.getEquipe1().getFranquia() + " x " + p.getEquipe2().getFranquia() + " " + p.getData());
        }
        
    }//GEN-LAST:event_btnBuscarPartidaActionPerformed

    private void cmbPartidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPartidaItemStateChanged
        // TODO add your handling code here:
        cmbJogador.removeAllItems();
        this.jogadores = new ArrayList();
        int index = cmbPartida.getSelectedIndex();
        if(index >= 0){
            Partida partida = this.partidas.get(index);
            Equipe e1 = partida.getEquipe1();
            Equipe e2 = partida.getEquipe2();
            
            ControllerJogador cj = new ControllerJogador();
            ArrayList<Jogador> jogadores = cj.getJogadorByEquipe(e1);
            for(Jogador j : jogadores){
                cmbJogador.addItem(j.getNome());
                this.jogadores.add(j);
            }
            
            jogadores = cj.getJogadorByEquipe(e2);
            System.out.println(e2.getFranquia());
            for(Jogador j : jogadores){
                cmbJogador.addItem(j.getNome());
                this.jogadores.add(j);
            }
        }        
    }//GEN-LAST:event_cmbPartidaItemStateChanged

    private void txtDataPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataPartidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPartida;
    private javax.swing.JButton btnCadastrarEstatisticaJogador;
    private javax.swing.JComboBox<String> cmbJogador;
    private javax.swing.JComboBox<String> cmbPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spnAssistencias;
    private javax.swing.JSpinner spnPontos;
    private javax.swing.JSpinner spnRebotes;
    private javax.swing.JSpinner spnRoubadas;
    private javax.swing.JSpinner spnTocos;
    private javax.swing.JSpinner spnTurnovers;
    private javax.swing.JTextField txtDataPartida;
    // End of variables declaration//GEN-END:variables
}
