/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ControllerEquipe;
import controllers.ControllerEstatistica;
import controllers.ControllerJogador;
import controllers.ControllerPartida;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.ArrayList;
import models.Equipe;
import models.EstatisticaJogador;
import models.Jogador;
import models.Partida;

/**
 *
 * @author emanu
 */
public class TelaBuscarJogador extends javax.swing.JInternalFrame {
    private MainFrame desktop;
    /**
     * Creates new form TelaCadastrarParida
     */
    public TelaBuscarJogador(MainFrame desktop) {
        initComponents();
        this.desktop = desktop;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProcuraNome = new javax.swing.JTextField();
        btnBuscarJogador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPosicao = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JLabel();
        txtAltura = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPontos = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRebotes = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAssistencias = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtRoubadas = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTocos = new javax.swing.JLabel();
        txtTurnovers = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnBuscarJogador1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTocos1 = new javax.swing.JLabel();
        txtTurnovers1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPosicao1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtIdade1 = new javax.swing.JLabel();
        txtAltura1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtPeso1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtPontos1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtRebotes1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtAssistencias1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtRoubadas1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtProcuraNome1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtNumPartidas = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtNumPartidas1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnSalvarArquivo = new javax.swing.JButton();
        txtArquivo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Partida");

        btnBuscarJogador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscarJogador.setText("Buscar");
        btnBuscarJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarJogadorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Salvar comparação:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNome.setText("None");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Posição:");

        txtPosicao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPosicao.setText("None");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Idade:");

        txtIdade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtIdade.setText("None");

        txtAltura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtAltura.setText("None");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Altura:");

        txtPeso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPeso.setText("None");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Peso:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel4.setText("X");

        txtPontos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPontos.setText("None");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Pontos:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Rebotes:");

        txtRebotes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRebotes.setText("None");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Assistências:");

        txtAssistencias.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtAssistencias.setText("None");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Roubadas:");

        txtRoubadas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRoubadas.setText("None");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Tocos:");

        txtTocos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTocos.setText("None");

        txtTurnovers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTurnovers.setText("None");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Turnovers:");

        btnBuscarJogador1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscarJogador1.setText("Buscar");
        btnBuscarJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarJogador1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Nome:");

        txtTocos1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTocos1.setText("None");

        txtTurnovers1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTurnovers1.setText("None");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Turnovers:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Nome:");

        txtNome1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNome1.setText("None");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Posição:");

        txtPosicao1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPosicao1.setText("None");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Idade:");

        txtIdade1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtIdade1.setText("None");

        txtAltura1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtAltura1.setText("None");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Altura:");

        txtPeso1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPeso1.setText("None");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Peso:");

        txtPontos1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPontos1.setText("None");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("Pontos:");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Rebotes:");

        txtRebotes1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRebotes1.setText("None");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Assistências:");

        txtAssistencias1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtAssistencias1.setText("None");

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Roubadas:");

        txtRoubadas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRoubadas1.setText("None");

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setText("Tocos:");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setText("N. Partidas:");

        txtNumPartidas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNumPartidas.setText("None");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("N. Partidas:");

        txtNumPartidas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNumPartidas1.setText("None");

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setText("Médias por jogo:");

        jLabel29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel29.setText("Médias por jogo:");

        jLabel30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel30.setText("Nome:");

        btnSalvarArquivo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvarArquivo.setText("Salvar");
        btnSalvarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarArquivoActionPerformed(evt);
            }
        });

        txtArquivo.setText("arquivo.csv");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTocos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260)
                        .addComponent(jLabel25)
                        .addGap(6, 6, 6)
                        .addComponent(txtTocos1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTurnovers, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250)
                        .addComponent(jLabel17)
                        .addGap(6, 6, 6)
                        .addComponent(txtTurnovers1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSalvarArquivo)
                            .addGap(39, 39, 39))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtRoubadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAssistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(223, 223, 223)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(6, 6, 6)
                                    .addComponent(txtAssistencias1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(6, 6, 6)
                                    .addComponent(txtRoubadas1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addComponent(jLabel18)
                                .addGap(6, 6, 6)
                                .addComponent(txtIdade1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jLabel19)
                                .addGap(6, 6, 6)
                                .addComponent(txtAltura1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jLabel20)
                                .addGap(6, 6, 6)
                                .addComponent(txtPeso1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRebotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel28))
                        .addGap(277, 277, 277)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(6, 6, 6)
                                .addComponent(txtPontos1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(6, 6, 6)
                                .addComponent(txtRebotes1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtProcuraNome, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(btnBuscarJogador))
                                    .addComponent(jLabel30))
                                .addGap(57, 57, 57)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(10, 10, 10)
                                .addComponent(txtNumPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(10, 10, 10)
                                .addComponent(txtNumPartidas1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(10, 10, 10)
                                .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6)
                                .addComponent(txtPosicao1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtProcuraNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(btnBuscarJogador1)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProcuraNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(txtProcuraNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(txtNumPartidas)
                    .addComponent(jLabel27)
                    .addComponent(txtNumPartidas1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNome)
                    .addComponent(jLabel8)
                    .addComponent(txtNome1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtPosicao)
                    .addComponent(jLabel10)
                    .addComponent(txtPosicao1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtIdade)
                    .addComponent(jLabel18)
                    .addComponent(txtIdade1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtAltura)
                    .addComponent(jLabel19)
                    .addComponent(txtAltura1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtPeso)
                    .addComponent(jLabel20)
                    .addComponent(txtPeso1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtPontos)
                    .addComponent(jLabel21)
                    .addComponent(txtPontos1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtRebotes)
                    .addComponent(jLabel22)
                    .addComponent(txtRebotes1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtAssistencias)
                    .addComponent(jLabel23)
                    .addComponent(txtAssistencias1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtRoubadas)
                    .addComponent(jLabel24)
                    .addComponent(txtRoubadas1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtTocos)
                    .addComponent(jLabel25)
                    .addComponent(txtTocos1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtTurnovers)
                    .addComponent(jLabel17)
                    .addComponent(txtTurnovers1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSalvarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarJogadorActionPerformed
        ControllerJogador cj = new ControllerJogador();
        String nome = txtProcuraNome.getText();
        Jogador jogador = cj.getJogadorByName(nome);
        txtNome.setText(jogador.getNome());
        txtPosicao.setText(jogador.getPosicao());
        txtIdade.setText(jogador.getIdade().toString() + " anos");
        txtAltura.setText(jogador.getAltura().toString() + " cm");
        txtPeso.setText(jogador.getPeso().toString() + " kg");
        
        ControllerEstatistica ce = new ControllerEstatistica();
        EstatisticaJogador ej = ce.getEstatisticaJogador(jogador);
        System.out.println(ej.getPontos());
        
        Integer numPartidas = ej.getNumPartidas();
        Double mediaPontos = (ej.getPontos().doubleValue()/numPartidas.doubleValue());
        Double mediaRebotes = (ej.getRebotes().doubleValue()/numPartidas.doubleValue());
        Double mediaAssistencias = (ej.getAssistencias().doubleValue()/numPartidas.doubleValue());
        Double mediaRoubadas = (ej.getRoubadas().doubleValue()/numPartidas.doubleValue());
        Double mediaTocos = (ej.getTocos().doubleValue()/numPartidas.doubleValue());
        Double mediaTurnovers = (ej.getTurnovers().doubleValue()/numPartidas.doubleValue());
        
        
        txtNumPartidas.setText(ej.getNumPartidas().toString());
        txtPontos.setText((mediaPontos).toString());
        txtRebotes.setText(mediaRebotes.toString());
        txtAssistencias.setText(mediaAssistencias.toString());
        txtRoubadas.setText(mediaRoubadas.toString());
        txtTocos.setText(mediaTocos.toString());
        txtTurnovers.setText(mediaTurnovers.toString());
        this.changeColor();
    }//GEN-LAST:event_btnBuscarJogadorActionPerformed

    private void btnBuscarJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarJogador1ActionPerformed
        // TODO add your handling code here:
        ControllerJogador cj = new ControllerJogador();
        String nome1 = txtProcuraNome1.getText();
        Jogador jogador = cj.getJogadorByName(nome1);
        txtNome1.setText(jogador.getNome());
        txtPosicao1.setText(jogador.getPosicao());
        txtIdade1.setText(jogador.getIdade().toString() + " anos");
        txtAltura1.setText(jogador.getAltura().toString() + " cm");
        txtPeso1.setText(jogador.getPeso().toString() + " kg");
        
        ControllerEstatistica ce = new ControllerEstatistica();
        EstatisticaJogador ej = ce.getEstatisticaJogador(jogador);
        System.out.println(ej.getPontos());
        
        Integer numPartidas = ej.getNumPartidas();
        Double mediaPontos = (ej.getPontos().doubleValue()/numPartidas.doubleValue());
        Double mediaRebotes = (ej.getRebotes().doubleValue()/numPartidas.doubleValue());
        Double mediaAssistencias = (ej.getAssistencias().doubleValue()/numPartidas.doubleValue());
        Double mediaRoubadas = (ej.getRoubadas().doubleValue()/numPartidas.doubleValue());
        Double mediaTocos = (ej.getTocos().doubleValue()/numPartidas.doubleValue());
        Double mediaTurnovers = (ej.getTurnovers().doubleValue()/numPartidas.doubleValue());
        
        
        txtNumPartidas1.setText(ej.getNumPartidas().toString());
        txtPontos1.setText((mediaPontos).toString());
        txtRebotes1.setText(mediaRebotes.toString());
        txtAssistencias1.setText(mediaAssistencias.toString());
        txtRoubadas1.setText(mediaRoubadas.toString());
        txtTocos1.setText(mediaTocos.toString());
        txtTurnovers1.setText(mediaTurnovers.toString());
        this.changeColor();
    }//GEN-LAST:event_btnBuscarJogador1ActionPerformed

    private void btnSalvarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarArquivoActionPerformed
        // TODO add your handling code here:
        String linha ,linha1, linha2;
        ArrayList<String> linhas = new ArrayList();
        linha = "Nome;Numero de Partidas;Posicao;Idade;Altura;Peso;Media de Pontos;Rebotes;Assistencias;Roubadas;Tocos;Turnovers";
        linhas.add(linha);
        if(txtNome.getText() != null){
            linha1 = txtNome.getText() +";"+txtNumPartidas.getText()+";"+txtPosicao.getText()
                    +";"+ txtIdade.getText()+";"+txtAltura.getText()+";"+txtPeso.getText()
                    +";"+txtPontos.getText()+";"+txtRebotes.getText()
                    +";"+txtAssistencias.getText()+";"+txtRoubadas.getText()+";"+txtTocos.getText()+";"+
                    txtTurnovers.getText();
            linhas.add(linha1);
        }
        if(txtNome1.getText() != null){
            linha2 = txtNome1.getText() +";"+txtNumPartidas1.getText()+";"+txtPosicao1.getText()
                    +";"+ txtIdade1.getText()+";"+txtAltura1.getText()+";"+txtPeso1.getText()
                    +";"+txtPontos1.getText()+";"+txtRebotes1.getText()
                    +";"+txtAssistencias1.getText()+";"+txtRoubadas1.getText()+";"+txtTocos1.getText()+";"+
                    txtTurnovers1.getText();
            linhas.add(linha2);
        }
        ControllerEstatistica ce = new ControllerEstatistica();
        Boolean retorno = ce.salvar(linhas, txtArquivo.getText());
        if(retorno){
            this.desktop.popUP("Arquivo salvo com sucesso!");
            this.dispose();
        }else{
            this.desktop.popUP("Erro ao salvar arquivo!");
        }
    }//GEN-LAST:event_btnSalvarArquivoActionPerformed
    
    public void changeColor(){
        
        if(Double.parseDouble(txtPontos.getText()) > Double.parseDouble(txtPontos1.getText())){
            txtPontos.setForeground(Color.GREEN);
            txtPontos1.setForeground(Color.red);
        }else if(Double.parseDouble(txtPontos.getText()) < Double.parseDouble(txtPontos1.getText())){
            txtPontos.setForeground(Color.red);
            txtPontos1.setForeground(Color.GREEN);
        }
        
        if(Double.parseDouble(txtRebotes.getText()) > Double.parseDouble(txtRebotes1.getText())){
            txtRebotes.setForeground(Color.GREEN);
            txtRebotes1.setForeground(Color.red);
        }else if(Double.parseDouble(txtRebotes.getText()) < Double.parseDouble(txtRebotes1.getText())){
            txtRebotes.setForeground(Color.red);
            txtRebotes1.setForeground(Color.GREEN);
        }
        
        if(Double.parseDouble(txtRoubadas.getText()) > Double.parseDouble(txtRoubadas1.getText())){
            txtRoubadas.setForeground(Color.GREEN);
            txtRoubadas1.setForeground(Color.red);
        }else if(Double.parseDouble(txtRoubadas.getText()) < Double.parseDouble(txtRoubadas1.getText())){
            txtRoubadas.setForeground(Color.red);
            txtRoubadas1.setForeground(Color.GREEN);
        }
        
        if(Double.parseDouble(txtAssistencias.getText()) > Double.parseDouble(txtAssistencias1.getText())){
            txtAssistencias.setForeground(Color.GREEN);
            txtAssistencias1.setForeground(Color.red);
        }else if(Double.parseDouble(txtAssistencias.getText()) < Double.parseDouble(txtAssistencias1.getText())){
            txtAssistencias.setForeground(Color.red);
            txtAssistencias1.setForeground(Color.GREEN);
        }
        
        if(Double.parseDouble(txtTocos.getText()) > Double.parseDouble(txtTocos1.getText())){
            txtTocos.setForeground(Color.GREEN);
            txtTocos1.setForeground(Color.red);
        }else if(Double.parseDouble(txtTocos.getText()) < Double.parseDouble(txtTocos1.getText())){
            txtTocos.setForeground(Color.red);
            txtTocos1.setForeground(Color.GREEN);
        }
        
        if(Double.parseDouble(txtTurnovers.getText()) < Double.parseDouble(txtTurnovers1.getText())){
            txtTurnovers.setForeground(Color.GREEN);
            txtTurnovers1.setForeground(Color.red);
        }else if(Double.parseDouble(txtTurnovers.getText()) > Double.parseDouble(txtTurnovers1.getText())){
            txtTurnovers.setForeground(Color.red);
            txtTurnovers1.setForeground(Color.GREEN);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarJogador;
    private javax.swing.JButton btnBuscarJogador1;
    private javax.swing.JButton btnSalvarArquivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel txtAltura;
    private javax.swing.JLabel txtAltura1;
    private javax.swing.JTextField txtArquivo;
    private javax.swing.JLabel txtAssistencias;
    private javax.swing.JLabel txtAssistencias1;
    private javax.swing.JLabel txtIdade;
    private javax.swing.JLabel txtIdade1;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtNome1;
    private javax.swing.JLabel txtNumPartidas;
    private javax.swing.JLabel txtNumPartidas1;
    private javax.swing.JLabel txtPeso;
    private javax.swing.JLabel txtPeso1;
    private javax.swing.JLabel txtPontos;
    private javax.swing.JLabel txtPontos1;
    private javax.swing.JLabel txtPosicao;
    private javax.swing.JLabel txtPosicao1;
    private javax.swing.JTextField txtProcuraNome;
    private javax.swing.JTextField txtProcuraNome1;
    private javax.swing.JLabel txtRebotes;
    private javax.swing.JLabel txtRebotes1;
    private javax.swing.JLabel txtRoubadas;
    private javax.swing.JLabel txtRoubadas1;
    private javax.swing.JLabel txtTocos;
    private javax.swing.JLabel txtTocos1;
    private javax.swing.JLabel txtTurnovers;
    private javax.swing.JLabel txtTurnovers1;
    // End of variables declaration//GEN-END:variables
}
