/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ControllerEquipe;
import controllers.ControllerEstatistica;
import controllers.ControllerJogador;
import controllers.ControllerPartida;
import java.awt.Color;
import java.util.ArrayList;
import models.Equipe;
import models.EstatisticaJogador;
import models.Jogador;
import models.Partida;

/**
 *
 * @author emanu
 */
public class TelaBuscarEquipe extends javax.swing.JInternalFrame {
    private MainFrame desktop;
    /**
     * Creates new form TelaCadastrarParida
     */
    public TelaBuscarEquipe(MainFrame desktop) {
        initComponents();
        this.desktop = desktop;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFranquia = new javax.swing.JTextField();
        btnBuscarFranquia = new javax.swing.JButton();
        txtCidade = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarFranquia1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtFranquia1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtConferencia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtVitorias = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDerrotas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPartidas = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPartidas1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCidade1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtConferencia1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtVitorias1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDerrotas1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Partida");

        btnBuscarFranquia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscarFranquia.setText("Buscar");
        btnBuscarFranquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFranquiaActionPerformed(evt);
            }
        });

        txtCidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCidade.setText("None");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel4.setText("X");

        btnBuscarFranquia1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscarFranquia1.setText("Buscar");
        btnBuscarFranquia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFranquia1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Franquia:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Franquia:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Cidade:");

        txtConferencia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtConferencia.setText("None");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Conferência:");

        txtVitorias.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtVitorias.setText("None");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Vitórias:");

        txtDerrotas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDerrotas.setText("None");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Derrotas:");

        txtPartidas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPartidas.setText("None");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Partidas:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Derrotas:");

        txtPartidas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPartidas1.setText("None");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Partidas:");

        txtCidade1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCidade1.setText("None");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Cidade:");

        txtConferencia1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtConferencia1.setText("None");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Conferência:");

        txtVitorias1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtVitorias1.setText("None");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Vitórias:");

        txtDerrotas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDerrotas1.setText("None");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtFranquia, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscarFranquia)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPartidas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDerrotas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtVitorias))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtConferencia))))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtFranquia1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscarFranquia1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPartidas1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDerrotas1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtVitorias1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtConferencia1))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(txtFranquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(txtFranquia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarFranquia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarFranquia1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtConferencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtPartidas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtVitorias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDerrotas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCidade1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtConferencia1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPartidas1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtVitorias1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtDerrotas1))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarFranquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFranquiaActionPerformed
        ControllerEquipe ce = new ControllerEquipe();
        Equipe equipe = ce.getByName(txtFranquia.getText());
        ControllerPartida cp = new ControllerPartida();
        ArrayList<Partida> partidas = cp.getEquipe(equipe);

        Integer numPartidas = partidas.size();
        Integer vitorias=0, derrotas = 0;
        
        for(Partida p : partidas){
            if(p.getEquipe1().getId() == equipe.getId()){
                if(p.getPontosEquipe1() > p.getPontosEquipe2()){
                    vitorias++;
                }
            }else if(p.getEquipe2().getId() == equipe.getId()){
                if(p.getPontosEquipe2() > p.getPontosEquipe1()){
                    vitorias++;
                }
            }
        }
        
        derrotas = numPartidas - vitorias;
        
        txtCidade.setText(equipe.getCidade());
        txtConferencia.setText(equipe.getConferencia());
        txtPartidas.setText(numPartidas.toString());
        txtVitorias.setText(vitorias.toString());
        txtDerrotas.setText(derrotas.toString());
        this.changeColor();
    }//GEN-LAST:event_btnBuscarFranquiaActionPerformed

    private void btnBuscarFranquia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFranquia1ActionPerformed
        // TODO add your handling code here:
        ControllerEquipe ce = new ControllerEquipe();
        Equipe equipe = ce.getByName(txtFranquia1.getText());
        ControllerPartida cp = new ControllerPartida();
        ArrayList<Partida> partidas = cp.getEquipe(equipe);

        Integer numPartidas = partidas.size();
        Integer vitorias=0, derrotas = 0;
        
        for(Partida p : partidas){
            if(p.getEquipe1().getId() == equipe.getId()){
                if(p.getPontosEquipe1() > p.getPontosEquipe2()){
                    vitorias++;
                }
            }else if(p.getEquipe2().getId() == equipe.getId()){
                if(p.getPontosEquipe2() > p.getPontosEquipe1()){
                    vitorias++;
                }
            }
        }
        
        derrotas = numPartidas - vitorias;
        
        txtCidade1.setText(equipe.getCidade());
        txtConferencia1.setText(equipe.getConferencia());
        txtPartidas1.setText(numPartidas.toString());
        txtVitorias1.setText(vitorias.toString());
        txtDerrotas1.setText(derrotas.toString());
        this.changeColor();
    }//GEN-LAST:event_btnBuscarFranquia1ActionPerformed
    
    public void changeColor(){
        try{
            if(Integer.parseInt(txtVitorias.getText()) > Integer.parseInt(txtVitorias1.getText())){
            txtVitorias.setForeground(Color.GREEN);
            txtVitorias1.setForeground(Color.red);
            }else if(Integer.parseInt(txtVitorias.getText()) < Integer.parseInt(txtVitorias1.getText())){
                txtVitorias.setForeground(Color.red);
                txtVitorias1.setForeground(Color.GREEN);
            }

            if(Integer.parseInt(txtDerrotas.getText()) < Integer.parseInt(txtDerrotas1.getText())){
                txtDerrotas.setForeground(Color.GREEN);
                txtDerrotas1.setForeground(Color.red);
            }else if(Integer.parseInt(txtDerrotas.getText()) > Integer.parseInt(txtDerrotas1.getText())){
                txtDerrotas.setForeground(Color.red);
                txtDerrotas1.setForeground(Color.GREEN);
            }
        }catch(NumberFormatException e){
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFranquia;
    private javax.swing.JButton btnBuscarFranquia1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel txtCidade;
    private javax.swing.JLabel txtCidade1;
    private javax.swing.JLabel txtConferencia;
    private javax.swing.JLabel txtConferencia1;
    private javax.swing.JLabel txtDerrotas;
    private javax.swing.JLabel txtDerrotas1;
    private javax.swing.JTextField txtFranquia;
    private javax.swing.JTextField txtFranquia1;
    private javax.swing.JLabel txtPartidas;
    private javax.swing.JLabel txtPartidas1;
    private javax.swing.JLabel txtVitorias;
    private javax.swing.JLabel txtVitorias1;
    // End of variables declaration//GEN-END:variables
}
