/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ControllerEquipe;
import controllers.ControllerEstatistica;
import controllers.ControllerJogador;
import controllers.ControllerPartida;
import java.util.ArrayList;
import models.Equipe;
import models.EstatisticaJogador;
import models.Jogador;
import models.Partida;

/**
 *
 * @author emanu
 */
public class TelaCadastrarEstatisticaJogador extends javax.swing.JInternalFrame {
    private MainFrame desktop;
    private ArrayList<Partida> partidas;
    private ArrayList<Jogador> jogadores;
    /**
     * Creates new form TelaCadastrarParida
     */
    public TelaCadastrarEstatisticaJogador(MainFrame desktop) {
        initComponents();
        this.desktop = desktop;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrarEstatisticaJogador = new javax.swing.JButton();
        cmbPartida = new javax.swing.JComboBox<>();
        txtDataPartida = new javax.swing.JFormattedTextField();
        btnBuscarPartida = new javax.swing.JButton();
        cmbJogador = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spnPontos = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spnRebotes = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        spnAssistencias = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        spnRoubadas = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spnTocos = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        spnTurnovers = new javax.swing.JSpinner();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Estatística do Jogador");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Patida");
        jLabel1.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 71, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Data da Partida");
        jLabel3.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 71, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        btnCadastrarEstatisticaJogador.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadastrarEstatisticaJogador.setText("Cadastrar");
        btnCadastrarEstatisticaJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEstatisticaJogadorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 40, 18, 74);
        getContentPane().add(btnCadastrarEstatisticaJogador, gridBagConstraints);

        cmbPartida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPartidaItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 41;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 145;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 4, 0, 74);
        getContentPane().add(cmbPartida, gridBagConstraints);

        txtDataPartida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.ipadx = 175;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 71, 0, 0);
        getContentPane().add(txtDataPartida, gridBagConstraints);

        btnBuscarPartida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscarPartida.setText("Buscar");
        btnBuscarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPartidaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 31;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 74);
        getContentPane().add(btnBuscarPartida, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 41;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 145;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 4, 0, 74);
        getContentPane().add(cmbJogador, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Jogador");
        jLabel6.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 71, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Pontos");
        jLabel7.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 71, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        spnPontos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 34, 0, 0);
        getContentPane().add(spnPontos, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Rebotes");
        jLabel8.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 71, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        spnRebotes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 34, 0, 0);
        getContentPane().add(spnRebotes, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Assistencias");
        jLabel9.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 71, 0, 0);
        getContentPane().add(jLabel9, gridBagConstraints);

        spnAssistencias.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 34, 0, 0);
        getContentPane().add(spnAssistencias, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Roubadas");
        jLabel10.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 71, 0, 0);
        getContentPane().add(jLabel10, gridBagConstraints);

        spnRoubadas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 34, 0, 0);
        getContentPane().add(spnRoubadas, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Tocos");
        jLabel11.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 71, 0, 0);
        getContentPane().add(jLabel11, gridBagConstraints);

        spnTocos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 34, 0, 0);
        getContentPane().add(spnTocos, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Turnovers");
        jLabel12.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 71, 0, 0);
        getContentPane().add(jLabel12, gridBagConstraints);

        spnTurnovers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 34, 0, 0);
        getContentPane().add(spnTurnovers, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarEstatisticaJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEstatisticaJogadorActionPerformed
        int indexJogador = cmbJogador.getSelectedIndex();
        int indexPartida = cmbPartida.getSelectedIndex();
        if(indexJogador >= 0 && indexPartida >= 0){
            ControllerEstatistica controllerEstatistica = new ControllerEstatistica();
            Jogador jogador = this.jogadores.get(indexJogador);
            Partida partida = this.partidas.get(indexPartida);
            Integer pontos = Integer.parseInt(spnPontos.getValue().toString());
            Integer rebotes = Integer.parseInt(spnRebotes.getValue().toString());
            Integer assistencias = Integer.parseInt(spnAssistencias.getValue().toString());
            Integer roubadas = Integer.parseInt(spnRoubadas.getValue().toString());
            Integer tocos = Integer.parseInt(spnTocos.getValue().toString());
            Integer turnovers = Integer.parseInt(spnTurnovers.getValue().toString());

            EstatisticaJogador estatisticaJogador = new EstatisticaJogador(partida, jogador, pontos, rebotes, assistencias, roubadas, tocos, turnovers);

            boolean cadastro = controllerEstatistica.createEstatisticaJogador(estatisticaJogador);
            if(cadastro){
                this.desktop.popUP("Cadastrado com sucesso!");
                this.dispose();
            }else{
                this.desktop.popUP("Erro ao cadastrar estatística! Por favor verifique os dados inseridos.");
            }
        }else{
            System.out.println(indexJogador);
            System.out.println(indexPartida);
        }
    }//GEN-LAST:event_btnCadastrarEstatisticaJogadorActionPerformed

    private void btnBuscarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPartidaActionPerformed
        // TODO add your handling code here:
        ControllerPartida cp = new ControllerPartida();
        String data = txtDataPartida.getText();
        this.partidas = new ArrayList();
        this.partidas = cp.getByData(data);
        cmbPartida.removeAllItems();
        for(Partida p : partidas){
            cmbPartida.addItem(p.getEquipe1().getFranquia() + " x " + p.getEquipe2().getFranquia() + " " + p.getData());
        }
        
    }//GEN-LAST:event_btnBuscarPartidaActionPerformed

    private void cmbPartidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPartidaItemStateChanged
        // TODO add your handling code here:
        cmbJogador.removeAllItems();
        this.jogadores = new ArrayList();
        int index = cmbPartida.getSelectedIndex();
        if(index >= 0){
            Partida partida = this.partidas.get(index);
            Equipe e1 = partida.getEquipe1();
            Equipe e2 = partida.getEquipe2();
            
            ControllerJogador cj = new ControllerJogador();
            ArrayList<Jogador> jogadores = cj.getJogadorByEquipe(e1);
            for(Jogador j : jogadores){
                cmbJogador.addItem(j.getNome());
                this.jogadores.add(j);
            }
            
            jogadores = cj.getJogadorByEquipe(e2);
            System.out.println(e2.getFranquia());
            for(Jogador j : jogadores){
                cmbJogador.addItem(j.getNome());
                this.jogadores.add(j);
            }
        }
        
    }//GEN-LAST:event_cmbPartidaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPartida;
    private javax.swing.JButton btnCadastrarEstatisticaJogador;
    private javax.swing.JComboBox<String> cmbJogador;
    private javax.swing.JComboBox<String> cmbPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spnAssistencias;
    private javax.swing.JSpinner spnPontos;
    private javax.swing.JSpinner spnRebotes;
    private javax.swing.JSpinner spnRoubadas;
    private javax.swing.JSpinner spnTocos;
    private javax.swing.JSpinner spnTurnovers;
    private javax.swing.JFormattedTextField txtDataPartida;
    // End of variables declaration//GEN-END:variables
}
