/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ControllerEquipe;
import controllers.ControllerPartida;
import java.util.ArrayList;
import models.Equipe;
import models.Partida;

/**
 *
 * @author emanu
 */
public class TelaCadastrarPartida extends javax.swing.JInternalFrame {
    private MainFrame desktop;
    /**
     * Creates new form TelaCadastrarParida
     */
    public TelaCadastrarPartida(MainFrame desktop) {
        initComponents();
        this.desktop = desktop;
        ControllerEquipe equipeController = new ControllerEquipe();
        ArrayList<Equipe> equipes = equipeController.getAll();
        for(Equipe e : equipes){
            cmbEquipe1.addItem(e.getFranquia());
            cmbEquipe2.addItem(e.getFranquia());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLocalPartida = new javax.swing.JTextField();
        spnPontosTime1 = new javax.swing.JSpinner();
        btnCadastrarParida = new javax.swing.JButton();
        cmbEquipe2 = new javax.swing.JComboBox<>();
        cmbEquipe1 = new javax.swing.JComboBox<>();
        spnPontosTime2 = new javax.swing.JSpinner();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Partida");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Franquia");
        jLabel1.setAlignmentX(0.5F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 26, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Franquia");
        jLabel3.setAlignmentX(0.5F);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Pontos");
        jLabel4.setAlignmentX(0.5F);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Pontos");
        jLabel5.setAlignmentX(0.5F);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 99, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Local");
        jLabel2.setAlignmentX(0.5F);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 156, -1, -1));

        txtLocalPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(txtLocalPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 184, 336, -1));

        spnPontosTime1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(spnPontosTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 95, 66, 30));

        btnCadastrarParida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadastrarParida.setText("Cadastrar");
        btnCadastrarParida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarParidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarParida, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 251, -1, -1));

        getContentPane().add(cmbEquipe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 54, 173, -1));

        getContentPane().add(cmbEquipe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 187, -1));

        spnPontosTime2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(spnPontosTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 97, 66, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLocalPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalPartidaActionPerformed

    private void btnCadastrarParidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarParidaActionPerformed
        ControllerEquipe ce = new ControllerEquipe();
        Equipe equipe1 = ce.get(cmbEquipe1.getSelectedItem().toString());
        Equipe equipe2 = ce.get(cmbEquipe2.getSelectedItem().toString());
        Integer pontosEquipe1 = Integer.parseInt(spnPontosTime1.getValue().toString());;
        Integer pontosEquipe2 = Integer.parseInt(spnPontosTime2.getValue().toString());
        String local = txtLocalPartida.getText();
        
        java.util.Date dt = new java.util.Date();

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String data = sdf.format(dt);
        
        ControllerPartida cp = new ControllerPartida();
        boolean cadastro = cp.create(equipe1, equipe2, pontosEquipe1, pontosEquipe2, local, data);
        
        if(cadastro){
            this.desktop.popUP("Cadastrado com sucesso!");
            this.dispose();
        }else{
            this.desktop.popUP("Erro ao cadastrar Partida! Por favor verifique os dados inseridos.");
        }
        

    }//GEN-LAST:event_btnCadastrarParidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarParida;
    private javax.swing.JComboBox<String> cmbEquipe1;
    private javax.swing.JComboBox<String> cmbEquipe2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner spnPontosTime1;
    private javax.swing.JSpinner spnPontosTime2;
    private javax.swing.JTextField txtLocalPartida;
    // End of variables declaration//GEN-END:variables
}
